### ISSUE TITLE
問題の整理

### ISSUE THREAD

**Issue by kanazawashihori** [enpit2016fun/minipbl_a#1]
開発依頼書から現状の業務フローと問題の洗い出しを行う

**Comment by s-morohara** [comment]
![default](https://cloud.githubusercontent.com/assets/4310006/17843472/4bd438fc-6869-11e6-9603-2c540b111a9b.jpg)

**Comment by s-morohara** [comment]
![default](https://cloud.githubusercontent.com/assets/4310006/17843475/54a92668-6869-11e6-97a4-ea3ee4489bdf.jpg)
